### ISSUE TITLE
PipelineRollout not recreating Pipeline

### ISSUE THREAD

**Issue by afugazzotto** [numaproj/numaplane#115]
**Describe the bug**
Numaplane reconciliation does not seem to happen after deleting and restoring a PipelineRollout.

**To Reproduce**

Via ArgoCD:
1. delete an existing PipelineRollout (you may need to remove the finalizer manually);
3. sync PipelineRollout again;
4. the reconciliation seems not to be triggered: nothing in the Numaplane logs (level set to Info) nor Pipeline child is deployed;
5. restarting the Numaplane controller will reconcile the PipelineRollout.

**Expected behavior**
A Pipeline should be created after applying a PipelineRollout spec to the cluster.

**Environment (please complete the following information):**

- Numaplane version of July 11th

**NOTE:**
Make sure this bug does not also happen for ISBServiceRollout.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
I wasn't able to reproduce this through adding PipelineRollout, deleting, re-adding. My thought is that based on the fact that you wrote "you may need to remove the finalizer manually", it has something to do with some scenario in which you'd have to remove the finalizer yourself. 

Since the log lines were on INFO, we don't know for sure if the subsequent reconciliation didn't happen, or if it did happen and it simply didn't create a new Pipeline for whatever reason and thus didn't log anything.

One thing to note is that if a reconciliation doesn't occur at all, it would be because the queue lock on that PipelineRollout for some reason didn't get released [here. ](https://github.com/numaproj/numaplane/blob/main/internal/controller/pipelinerollout_controller.go#L225) I guess we need to make sure that that can't happen (like no indefinite blocking).

**Comment by afugazzotto** [comment]
I was able to reproduce the issue. At the first deletion after the Numaplane Controller is restarted, the issue is not present. However, deleting again the PipelineRollout will cause the issue. I enabled debug logs and attached is a file describing the timeline of operations and relative logs.
[Debug logs and timeline.txt](https://github.com/user-attachments/files/16238314/Debug.logs.and.timeline.txt)

**Comment by juliev0** [comment]
This is caused by the rate limiting of the queue. It's using an exponential backoff algorithm, and that's causing it to get delayed more and more with all of the subsequent requests coming in. For now, I will change it to not use rate limiting when `Reconcile()` is called, and we can revisit that issue later.
