### ISSUE TITLE
Spec Hash Annotation and AutoHealing

### ISSUE THREAD

**Issue by afugazzotto** [numaproj/numaplane#64]
# Summary

Pipeline/ISBService need to auto heal if changed manually even if rollouts are unchanged by comparing annotation hash of spec.

# Details

To avoid performing multiple expensive `update` calls on reconciliation, we will keep track of the following 3 hash strings:
- `hashA`: previous PipelineRollout pipeline spec hash (the one stored in the PipelineRollout annotations)
- `hashB`: current PipelineRollout pipeline spec that we calculate at reconciliation
- `hashC`: hash of Pipeline spec on the cluster without the Lifecycle field (we need to calculate this everytime)

for the following scenarios:
- If `hashA` == `hashB` && `hashC` == `hashB`: there are no changes made to the PipelineRollout nor to the Pipeline; therefore, we do not need to perform any updates
- If `hashA` == `hashB` && `hashC` != `hashB`: there are no changes made to the PipelineRollout; however, the Pipeline on the cluster was changed. Therefore, we need to autoheal the Pipeline by applying the PipelineRollout pipeline spec to overwrite the Pipeline CR on the cluster.
- If `hashA` != `hashB` the PipelineRollout pipeline spec has changed and we need to apply it. Note: no need to check `hashC` in this case.

**NOTE:** instead of computing `hashC` by reading the Pipeline everytime and calculating the hash, we considered gettting the `hashC` from the Pipeline since Numaflow already stores it. However, this includes the Lifecycle field which does not work for us since we want to exclude pausing state from the hash.
Therefore, we can either:
- A. read the Pipeline CR and calculate `hashC` OR
- B. read the Pipeline CR and compare the spec directly against the PipelineRollout pipeline spec.

Case B may not be any more performant than case A since for both cases we need to read the pipeline and, because we are using RawExtension type, we will probably have to perform marshalling/unmarshalling operations to convert to map and then perform deep comparisons. Hashing and comparing strings may be more performant. Appropriate performance testing should be performed if this is a great concern.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
Thanks for all of this write up and in-depth analysis. I have some questions for clarification.

What are the advantages of this plan over the one I mentioned earlier?: Don't store annotation, and simply compare intended spec (including pause designation (so, this would be right before we're about to apply it)) with actual running spec (not the one that Numaflow stores in its annotation)?

**Comment by juliev0** [comment]
I see you already have a PR so I don't want to mess up what you've already done, but here are my thoughts in case it makes sense to do some refactoring later at least (which I'd be happy to do).

In my mind, the true difference is "desired PipelineRollout spec" vs "running Pipeline". Those may be different because:
1. the PipelineRollout spec has changed
2. we need to auto-heal a manual change that was made to the Pipeline  

**In either case, why not safely make our change without data loss?**

Therefore, we could simply compare those 2 things and not worry about the previously applied PipelineRollout spec.

As far as performance comparison:
1. In the "no hash annotation" model, there are no K8S API Update calls to update the Rollout spec
2. In the "hash annotation" model, in the case that the Rolllout spec has changed, there is no calculation of the current running child object and comparison between them

I believe the first one is more of an optimization. It is the saving of a network call, which is more impactful than a calculation. Also, the second one only helps in the case of the Rollout spec having changed, which I believe would be the minority of `Reconcile()` calls. More often, I would think we would see `Reconcile()` called because the status of a child object changed.

cc @xdevxy

**Comment by afugazzotto** [comment]
@juliev0 I'm not sure what you mean by `1. In the "no hash annotation" model, there are no K8S API Update calls to update the Rollout spec`. I think that even without hash annotations, if there are changes to either the PipelineRollout or the Pipeline, there will be a call to update the CR.
I think that what this boils down to is that we either simplify implementation or gain some performance improvements. However, has mentioned in the issue description, we may want to do performance testing to really understand how much we gain or lose with either implementations. I think at this time we do not have the bandwidth to do those tests.
If possible, you, me and @xdevxy should discuss verbally pros and cons of both ideas to clarify the auto healing and hashing features.

**Comment by juliev0** [comment]
> I think that even without hash annotations, if there are changes to either the PipelineRollout or the Pipeline, there will be a call to update the CR.

So, there will be an Update made to the PipelineRollout before the reconciler gets it (because ArgoCD applied it), then yes there is that call, but that's outside of us. But then [here](https://github.com/numaproj/numaplane/blob/58d4a5349b765e4b8f04eb8d962dfc59bfa179aa/internal/controller/pipelinerollout_controller.go#L300) we are doing an additional Update to the Rollout when the Annotation changes.

**Comment by juliev0** [comment]
Thanks so much for continuing the conversation with me. 

> If this is a concern, would it make sense to store the hash in the status (instead of the annotations) since we always update the status anyways?

That's a possibility. Honestly, I'm not terribly concerned about the Update(), but I mentioned it because the main reason for going with the other approach seemed to be performance.

I think I may be okay with keeping the existing logic that uses the annotation. But my thought is that our overall code structure should be:
```
If Pipeline doesn't exist, create it
else:
   if !(currentRolloutSpecHash == pipelineRollout.Annotations[apiv1.KeyHash] && currentRolloutSpecHash == pipelineSpecHash)   <-- this is the only place we need a comparison and not later on
     perform lifecycle management (i.e. either pause pipeline, continue waiting for it to pause, or unpause and update spec)
processPipelineStatus()
```

What do you think?

**Comment by afugazzotto** [comment]
> Thanks so much for continuing the conversation with me.
> 
> > If this is a concern, would it make sense to store the hash in the status (instead of the annotations) since we always update the status anyways?
> 
> That's a possibility. Honestly, I'm not terribly concerned about the Update(), but I mentioned it because the main reason for going with the other approach seemed to be performance.
> 
> I think I may be okay with keeping the existing logic that uses the annotation. But my thought is that our overall code structure should be:
> 
> ```
> If Pipeline doesn't exist, create it
> else:
>    if !(currentRolloutSpecHash == pipelineRollout.Annotations[apiv1.KeyHash] && currentRolloutSpecHash == pipelineSpecHash)   <-- this is the only place we need a comparison and not later on
>      perform lifecycle management (i.e. either pause pipeline, continue waiting for it to pause, or unpause and update spec)
> processPipelineStatus()
> ```
> 
> What do you think?

That makes sense. For now, `processPipelineStatus` is called in `applyPipelineSpec` which is also called in multiple places in the `reconcile` func. This is what I meant earlier that we should change that logic and maybe have few functions to improve how and when to perform the operations we want. I'm honestly trying to make few small changes at the time but once I'm done with the urgent tasks for this sprint, I'll restructure that code. I also plan to make unit tests functions a bit more reusable now that we have more cases and some are similar.
